services:
  - type: web
    name: agrisolve-api
    runtime: python
    region: oregon
    rootDir: backend
    buildCommand: bash render_build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
